### ISSUE TITLE
C: geo has stopped

### ISSUE THREAD

**Issue by Globalcaching** [culmor30/cgeo-wear#16]
I have a motorola smartwatch with android wear. I installed c:geo wear on my smartphone and press the button 'Android wear' in c: geo. However, every time I try to do this, c:geo stops.

**Comment by culmor30** [comment]
Thanks, I'll look into it.

**Comment by culmor30** [comment]
Oops. I always hit 'close' by accident.

**Comment by Globalcaching** [comment]
Great, thanks. By the way. My friend has a LG Watch R, he has the same problem.

**Comment by Globalcaching** [comment]
I also reported this at c:geo and today they said they fixed it. So, I will wait for the next version of c:geo to see if this is the case. But this could mean that this is not an issue of c:geo wear, but c:geo

**Comment by Globalcaching** [comment]
bug is solved in c:geo itself.
